### ISSUE TITLE
Copy news link to clipboard onLongPress()

### ISSUE THREAD

**Issue by himanshusingh335** [himanshusingh335/check_my_news#1]
1. Enable onLongPress() in the list tile.
2. Add functionality to copy the news link to the clipboard (using [clipboard plugin](https://pub.dev/packages/clipboard)) inside onLongPress().
3. Build a snackbar that will notify the users that the link has been copied to the clipboard.

**Comment by agent515** [comment]
@himanshusingh335 I would like to take up this issue.

**Comment by himanshusingh335** [comment]
I have assigned the issue to you @agent515, Happy coding
